<a href="https://colab.research.google.com/github/Normanthen/My-Python/blob/main/Norman_Deep_Learning.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# All-ones or all-zeros tensor

In [1]:
import tensorflow as tf

x = tf.ones(shape =(2, 1))
print(x)

tf.Tensor(
[[1.]
 [1.]], shape=(2, 1), dtype=float32)


In [2]:
x = tf.zeros(shape=(2,1))
print(x)

tf.Tensor(
[[0.]
 [0.]], shape=(2, 1), dtype=float32)


# Random Tensor

In [3]:
x = tf.random.normal(shape=(3, 1), mean=0., stddev=1.)
print(x)

tf.Tensor(
[[0.25422055]
 [1.6433278 ]
 [0.33914182]], shape=(3, 1), dtype=float32)


In [6]:
x = tf.random.uniform(shape=(3, 1), minval= 0, maxval = 1)
print(x)

tf.Tensor(
[[0.19204724]
 [0.04520023]
 [0.56684005]], shape=(3, 1), dtype=float32)


# NumPy arrays are assignable