<a href="https://colab.research.google.com/github/Normanthen/My-Python/blob/main/Norman_Deep_Learning.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# All-ones or all-zeros tensor

In [9]:
import tensorflow as tf

x = tf.ones(shape =(2, 1))
print(x)

tf.Tensor(
[[1.]
 [1.]], shape=(2, 1), dtype=float32)


In [10]:
x = tf.zeros(shape=(2,1))
print(x)

tf.Tensor(
[[0.]
 [0.]], shape=(2, 1), dtype=float32)


# Random Tensor

In [11]:
x = tf.random.normal(shape=(3, 1), mean=0., stddev=1.)
print(x)

tf.Tensor(
[[ 0.62585187]
 [ 1.7007918 ]
 [-1.1734303 ]], shape=(3, 1), dtype=float32)


In [12]:
x = tf.random.uniform(shape=(3, 1), minval= 0, maxval = 1)
print(x)

tf.Tensor(
[[0.44770825]
 [0.48903   ]
 [0.7100054 ]], shape=(3, 1), dtype=float32)


# NumPy arrays are assignable

In [13]:
import numpy as np
x = np.ones(shape=(2,2))
x[0,0] = 0.

# TensorFlow tensors are not assignable


In [14]:
#x = tf.ones(shape=(2,2))
#x[0, 0] = 0.

# Creating a TensorFlow variable

To train a model, we'll need to update its state, which is a set of tensors. `tf.variable` is the class meant to manage modifiable state in TensorFlow.