# What does -1 mean in numpy reshape? #
**Source:** [Stack Exchange Question](https://stackoverflow.com/questions/18691084/what-does-1-mean-in-numpy-reshape?newreg=21371eea7ee54f7a8a55053ea927b629)

## Answer 1

**Source**: [lonewolf's answer](https://stackoverflow.com/a/59071031/23999558)

*"It simply means that you are not sure about what number of rows or columns you can give and you are asking numpy to suggest number of column or rows to get reshaped in"*

Here, in this documentation about `np.reshape`, Numpy provides the last example for -1:

[`np.reshape` documentation](https://docs.scipy.org/doc/numpy/reference/generated/numpy.reshape.html)

Check the code below and its output to better understand about (-1)

In [2]:
import numpy as np

a = np.matrix([[1,2,3,4],[5,6,7,8]])
print("Without reshaping: ")
print(a)

b = np.reshape(a,-1)
print("HERE We don't know about what number we should give to row/col")
print("Resaphing as (a,-1) :")
print(b)

c = np.reshape(a,(-1,2))
print("Here We just know about number of columns")
print(c)

d = np.reshape(a,(2,-1))
print("Here We just know about number of rows")
print("Reshaping as (a,(2,-1))")
print(d)

Without reshaping: 
[[1 2 3 4]
 [5 6 7 8]]
HERE We don't know about what number we should give to row/col
Resaphing as (a,-1) :
[[1 2 3 4 5 6 7 8]]
Here We just know about number of columns
[[1 2]
 [3 4]
 [5 6]
 [7 8]]
Here We just know about number of rows
Reshaping as (a,(2,-1))
[[1 2 3 4]
 [5 6 7 8]]


# Using the Python `*args` and `**kwargs`  variable in Function Definitions

Source: [Real Python](https://realpython.com/python-kwargs-and-args/)

## Args

You simply pass a list or a set of all the arguments to your function. So for `my_sum()`, you could pass a list of all the integers you need to add:

In [3]:
def my_sum(my_integers):
    results=0
    for x in my_integers:
        results +=x
    
    return results

list_of_integers = [1, 2, 3]
print(my_sum(list_of_integers))

6


`*args` allows you to pass a varying number of positional arguments. Take the following example:

In [4]:
def my_sum(*args):
    result = 0
    # Iterating over the python args tuple
    for x in args:
        result += x
    return result

print(my_sum(1, 2, 3))


6


In this example, you're no longer passing a list to `my_sum()`. Instead, you're passing three different positional arguments. `my_sum()` takes all the paramter that are provided in the input and packs them all into a single iterable object named `*args`.

Note that `*args` **ist just a name**. You're not required to use the name `args`. You can choose any names that you prefer, such as `*integers`:

In [5]:
def my_sum(*integers):
    result = 0
    for x in integers:
        result +=x
    return result

print(my_sum(1,2,3))

6


The function still works, even if you pass the iterable object as `integers` instead of `args`. All that matters here is that you use **the unpacking operator (*)**.

Bear in mind that the iterable object you'll get using is the unpacking operator `*` is not a `list` but a `tuple`. A `tuple` is similiar to a `list` in that they both support slicing and iteration. However, `tuple` are very different in at least one aspect: `list` are mutable, while `tuple` aren't. To test this, run the following code. This script tries to change a value of a list:

In [6]:
my_list = [1,2,3]
my_list[0] = 9
print(my_list)

[9, 2, 3]


The value located at the very first index is updated to `9` as you can see above.

Now, try to do the same with a tuple:

In [7]:
#my_tuple = (1,2,3)
#my_tuple[0] = 9
#print(my_tuple)

```
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
Cell In[10], line 2
      1 my_tuple = (1,2,3)
----> 2 my_tuple[0] = 9
      3 print(my_tuple)

TypeError: 'tuple' object does not support item assignment

```

You see that the python interpreter returns an error.

This is because a tuple is an immutable object, and its values cannot be changed after assignment. Keep this in mind you're working with tuples and `*args`.

## Kwargs (Keyword Arguments)

Source: [Real python](https://realpython.com/python-kwargs-and-args/)

`**kwargs` works just like `*arg`, but instead of accepting positional arguments it accepts keyword (or **named**) arguments. Take the following example:

In [8]:
def concatenate(**kwargs):
    result=""
    #iterating over the python kwargs dictionary
    for arg in kwargs.values():
        result += arg
    return result

print(concatenate(a="Real", b="Python", c='is', d="Great", e="!"))

RealPythonisGreat!


Like `arg`, `kwargs` is just a name that can be changed to whatever you want. Again, what is important here is the use of the **unpacking operator** (**).

So, the previous example could be written like this:

In [9]:
def concatenate(**words):
    result =""
    for arg in words.values():
        result += arg
    return result

print(concatenate(a="Real", b="Python", c='is', d="Great", e="!"))

RealPythonisGreat!


Note that in the example above the iterable object is standard `dict`. If you iterate over the dictionary and want to return its values like in the example shown, then you must use `.values()`.

In fact if you forget to use this method, you will find yourself iterating through the **keys** of your python kwargs dictionary instead, like in the following example: 

In [10]:
def concatenate(**kwargs):
    result = ""
    #iterating over the keys of the python kwargs dictionary
    for arg in kwargs:
        result += arg
    return result

print(concatenate(a="Real", b="Python", c='is', d="Great", e="!"))

abcde


As you can see, if you don't specify your `.values()`, your function will iterate over the keys of your Python `**kwargs` dictionary, returning the wrong results.

# Empty list []

**Source:**

- [freecodecamp](https://www.freecodecamp.org/news/python-empty-list-tutorial-how-to-create-an-empty-list-in-python/)
- [Geeksforgeeks](https://www.geeksforgeeks.org/declare-an-empty-list-in-python/)

## Using Square Brackets
You can crate an empty list with an empty pair of square brackets, like this:

`<var>=[]`

We assign the empty list to a variable to use it later in our program. For example:

`num = []`

The empty list will have length `0`, as you can see right here:

In [11]:
num = []
len(num)

0

Empty list are **falsy** values, which means that they evaluate to `false` in a boolean context

In [12]:
bool(num)

False

## Adding Elements to an Empty list

You can add elements to an empty list using the methods `append()` and `insert()`:

- `append()` adds the element to the end of the list.
- `insert()` adds the element at the particular index of the list that you choose.

Since list can be either truthy or falsy values depending on whether they are empty or not when they are evaluated, you can use them in conditionals like this:

In [13]:
if num:
    print("This list is not empty")
else:
    print("This list is empty")

This list is empty


Because the list was empty, so it evaluetes to False

In general:
- If the list is not empty, it evaluates to `True`, so the if clause is executed.
- If the list is not empty, it evaluates to `False`, so the else clause is executed.

## Example

In the example below, We create an empty list and assign it to the variable `num`. Then, using a for loop, we add a sequence of elements (integers) to the list that was initially empty:

In [14]:
num = []
for i in range(3,15,2):
    num.append(i)
print(num)

[3, 5, 7, 9, 11, 13]


As you can see, We check the value of the variable using `print(num)` to see if the items were appended successfully and confirm that the list `num` is not empty anymore.

**Tip:** We commonly use `append()` to add the first element to an empty list, but you can also add this element calling the `insert()` method with index `0`:

In [15]:
num = []
num.insert(0, 1.5) # add the float 1.5 at index o
num

[1.5]

## Using the `list()` Constructor

Alternatively, you can create an empty list with the type constructor `list()`, which creates a new list object.

According to the [Python Documentation](https://docs.python.org/3/library/stdtypes.html#list):
> If no argument is given, the constructor creates a new empty list, [].

**Tip**: This creates a new list object in memory and since We didn't pass any arguments to `list()`, an empty list will be created.

For example:

`num = list()`

This empty list will have length `0`, as you can see right here:

In [16]:
num =  list()
len(num)

0

And it is a **falsy** value when it is empty (it evaluates to `False` in a boolean context):

In [17]:
bool(num)

False

### Example

This is a fully functional list, so we can add elements to it:

In [18]:
for i in range(3,15,2):
    num.append(i)

num

[3, 5, 7, 9, 11, 13]

As you can see above, the result will be a non-empty list.

## Use Cases

- We typically use `list()` to create list from existing iterables such as strings, dictionaries, or tuples.
- You will commonly see square brackets `[]` being used to create empty lists in Python because this syntax is more concise and faster. 

## Efficiency

`[]` is faster than `list()`...

**But how much faster?**

Let's check their time efficiencies using the [timeit](https://docs.python.org/3/library/timeit.html#module-timeit) module.

To use this module in your Python program, you need to import it.

Specifically, we will use the [timeit function](https://docs.python.org/3/library/timeit.html#timeit.timeit) from this module, which you can call with this syntax:

`timeit.timeit('<code>', numbers=<num_repetitions>)`

- `<code>`: Code that you want to test

- `<num_repetitions>` :  How many times you want to repeat the code

**Tip:** The code is repeated several times to reduce time differences that may arise from external factors such as other processes that might be running at that particular moment. This makes the results more reliable for comparison purposes.

In [19]:
import timeit

We start testing each syntax

**Testing `[]`:**

In [20]:
timeit.timeit('[]',number=10**4)

0.00040210000042861793

**Testing `list()`:**

In [21]:
timeit.timeit('list()',number=10**4)

0.0008001999999578402

You can see that `[]` is much faster than `list()`. There was difference of approximately `0.0002` seconds in this test:

**Why is `list()` less eficient than `[]` if they do exactly the same thing?**

Well.. `list()` is slower because it requires looking up the name of the function, calling it, and then creating the list object in memory. In contrast, `[]` is like a "shortcut" that doesn't require so many intermediate steps to create the list in memory.

# Boolean Indexing

- [Copilot Answers 1](../TE%20Transport%20Calculation/TiS/Bands/CopilotAnswers-20240405-211041.pdf)
- [Copilot Answers 2](../TE%20Transport%20Calculation/TiS/Bands/CopilotAnswers-20240405-211355.pdf)
- [NumPy Documentation](https://numpy.org/doc/stable/user/basics.indexing.html#boolean-array-indexing)
- [Programriz](https://www.programiz.com/python-programming/numpy/boolean-indexing)
- [Google search on Stackexchange](https://www.google.com/search?q=Conditional+indexing+operation+python+site:stackoverflow.com&sca_esv=ebc234f9216407d8&sxsrf=ACQVn09LQpbpbXzJRaUIXCgN-Vpa_a5zXQ:1712326020273&sa=X&ved=2ahUKEwj26bXBn6uFAxXKyDgGHY4FAwIQrQIoBHoECB4QBQ&biw=1272&bih=598&dpr=1.5)


# NumPy Joining Array
- [W3school](https://www.w3schools.com/python/numpy/numpy_array_join.asp)
- [Numpy Documentation](https://numpy.org/doc/stable/reference/generated/numpy.concatenate.html) (`np.concatenate`)

## Joining NumPy Arrays

Joining means putting contents of two or more arrays in a single array.

We pass a sequence of arrays that we want to join to the `concatenate` function, along with the axis. If the axis is not explicitly passed, it is taken as 0:

**Join two arrays**

In [22]:
arr1 = np.array([1,2,3])

arr2 = np.array([4,5,6])

arr  = np.concatenate((arr1,arr2))

print(arr)

[1 2 3 4 5 6]


**Join two 2-D arrays along rows (axis =1):**

In [23]:
arr1 = np.array([[1,2],[3,4]])
arr2 = np.array([[5,6],[7,8]])
arr  = np.concatenate((arr1,arr2),axis=1) 
print(arr)

[[1 2 5 6]
 [3 4 7 8]]


## Joining Arrays Using Stack Functions

Stacking is same as concatenation, the only difference is that stacking is done along with a new axis.

We can concatenate two 1-D arrays along the second axis which would result in putting them one over the other, i.e. stacking.

We pass a sequence of arrays that we want to join to the `stack()` method along with the axis. If axis is not explicitly passed it is taken as 0:

In [24]:
arr1 = np.array([1,2,3])

arr2 = np.array([4,5,6])

arr  = np.stack((arr1,arr2),axis=1)

print(arr)

[[1 4]
 [2 5]
 [3 6]]


**Stacking Along Rows**

NumPy provides a helper function: `hstack` to stack along rows

In [25]:
arr = np.hstack((arr1,arr2))
print(arr)

[1 2 3 4 5 6]


**Stacking Along Columns**

NumPy provides a helper function: `vstack()` to stack along columns

In [26]:
arr = np.vstack((arr1,arr2))
print(arr)

[[1 2 3]
 [4 5 6]]


**Stacking Along Height (depth)**

Numpy provides a helper function: `dstack` to stack along height which is the same as depth.

In [27]:
arr = np.dstack((arr1,arr2))
print(arr)

[[[1 4]
  [2 5]
  [3 6]]]


# Finding the last element of NumPy Array

- [Finxter blog](https://blog.finxter.com/5-best-ways-to-access-the-last-element-of-a-python-numpy-array/)

- [GiS Stack Exchange answers](https://gis.stackexchange.com/questions/102219/print-last-digit-in-numpy-array)

- [W3school1](https://www.tutorialspoint.com/how-to-select-elements-from-numpy-array-in-python)

- [W3school2](https://www.tutorialspoint.com/How-to-get-the-last-element-of-a-list-in-Python)

- [Numpy Documentation](https://numpy.org/devdocs/user/absolute_beginners.html)

## Method 1: Using Negative Indexing

Negative indexing allows us to count from the end of the array. In NumPy, `array[-1]` will return the last element of the array. 

In [28]:
# Create a NumPy array
arr = np.array([1,2,3,4,5])

# Access the last element
last_element = arr[-1]
print(last_element)
type(last_element)

5


numpy.int32

## Method 2: Using the `item` Method

The `item()` method in NumPy can be used to retrieve a specific element from an array. By passing `-1` as the argument, it retrieves the last element. This method is beneficial when you require the native Python scalar type instead of NumPy type.

In [29]:
# Access the last element as a native Python type
last_element = arr.item(-1)
print(last_element)
type(last_element)

5


int

## Method 3: Using the `take` function

The `take()` is a flexible way to access elements of a NumPy array by specifying the indices. To retrieve the last element you can pass `-1` as the index to the `take()` function.

In [30]:
last_element =  np.take(arr,-1)
print(last_element)
type(last_element)

5


numpy.int32

## Method 4: Using the `index` Function with `shape`

Another way to access the last element of a NumPy array is to use the array's shape to calculate the index of the last element. The `shape` attribute returns a tuple that represents the size of each dimension of the array. You can use this compute the index of the last element.

In [31]:
#Calculate the index of the last element
last_index = arr.shape[0]-1

#Access the last element
print(arr.shape[0])
last_element = arr[last_index]
print(last_element)
type(last_element)

5
5


numpy.int32

## Method 5: Using the `flat` Attribute (One-Liner)

The `flat` attributes provides a 1-D iterator over the array. We can combine this with the `[-1]` index to get the last element in a clean one-liner. 

In [32]:
# Access the last element using the `flat` attribute
last_element = arr.flat[-1]
print(last_element)
type(last_element)

5


numpy.int32

# Type Hinting
**Sources:**
- [Real Python](https://realpython.com/lessons/type-hinting/)
- [Stack Exchange](https://stackoverflow.com/questions/21930035/how-to-write-help-description-text-for-python-functions) 

**Type hinting** is a formal solution to statically indicate the type of a value within your Python code.

Here is an example of adding type information to a function. You annotate the arguments and the return value:

In [33]:
def greet(name:str) -> str:
    return "Hello, " + name

print(greet("norman"))

Hello, norman


The `name: str` syntax indicates the `name` argument should be of type `str`. The `->` syntax indicates the `greet()` will return a string.

The following example function turns a text string into a headline by adding proper capitalization and a decorative line:

In [34]:
def headline(text, align=True):
    if align:
        return f"{text.title()}\n{'-'*len(text)}"
    else:
        return f" {text.title()} ".center(50, "o")
    
print(headline("Python type checking"))
print(headline("python type checking", align=False))

Python Type Checking
--------------------
oooooooooooooo Python Type Checking oooooooooooooo


Now add type hints by annotating the arguments and the return value as follows

In [35]:
def headline(text:str, align: bool=True) -> str:
    if align:
        return f"{text.title()}\n{'-'*len(text)}"
    else:
        return f" {text.title()} ".center(50, "o")
    
help(headline)

Help on function headline in module __main__:

headline(text: str, align: bool = True) -> str



# Mr. P Solver Tips
Link: [OneNote Page](https://onedrive.live.com/view.aspx?resid=9FF0E855772065F5%211062&id=documents&wd=target%28Work%20Notebook%27s%20Backup%2FPython%20Drill.one%7C47627FDD-3176-456E-A8E8-87569F44B05A%2FThe%20Full%20Python%20Tutorial%7C89ECC2F1-CF74-4760-B2B2-1BBE8094EDFF%2F%29)

## Variables

In [40]:
x1 = 'ca{}t'.format('s')
print(x1)

age  = 25.453386632646
x2 = 'I am {:.2f} years old'.format(age)
print(x2)
x3 = 'I am {:.0f} years old'.format(age)
print(x3)

cast
I am 25.45 years old
I am 25 years old


# Docstring

- [Stack Exchange](https://stackoverflow.com/questions/21930035/how-to-write-help-description-text-for-python-functions)

# `type()` Built-in Function

Source
- [Stack Exchange Answers](https://stackoverflow.com/questions/402504/how-to-determine-a-python-variables-type)

# Python NOT EQUAL Operator

Source:
[geeksforgeeks](https://www.geeksforgeeks.org/python-not-equal-operator/)