# What does -1 mean in numpy reshape? #
**Source:** [Stack Exchange Question](https://stackoverflow.com/questions/18691084/what-does-1-mean-in-numpy-reshape?newreg=21371eea7ee54f7a8a55053ea927b629)

## Answer 1

**Source**: [lonewolf's answer](https://stackoverflow.com/a/59071031/23999558)

*"It simply means that you are not sure about what number of rows or columns you can give and you are asking numpy to suggest number of column or rows to get reshaped in"*

Here, in this documentation about `np.reshape`, Numpy provides the last example for -1:

[`np.reshape` documentation](https://docs.scipy.org/doc/numpy/reference/generated/numpy.reshape.html)

Check the code below and its output to better understand about (-1)

In [2]:
import numpy as np

a = np.matrix([[1,2,3,4],[5,6,7,8]])
print("Without reshaping: ")
print(a)

b = np.reshape(a,-1)
print("HERE We don't know about what number we should give to row/col")
print("Resaphing as (a,-1) :")
print(b)

c = np.reshape(a,(-1,2))
print("Here We just know about number of columns")
print(c)

d = np.reshape(a,(2,-1))
print("Here We just know about number of rows")
print("Reshaping as (a,(2,-1))")
print(d)

Without reshaping: 
[[1 2 3 4]
 [5 6 7 8]]
HERE We don't know about what number we should give to row/col
Resaphing as (a,-1) :
[[1 2 3 4 5 6 7 8]]
Here We just know about number of columns
[[1 2]
 [3 4]
 [5 6]
 [7 8]]
Here We just know about number of rows
Reshaping as (a,(2,-1))
[[1 2 3 4]
 [5 6 7 8]]


# Boolean Indexing
- [NumPy Documentation](https://numpy.org/doc/stable/user/basics.indexing.html#boolean-array-indexing)
- [Programriz](https://www.programiz.com/python-programming/numpy/boolean-indexing)
- [Google search on Stackexchange](https://www.google.com/search?q=Conditional+indexing+operation+python+site:stackoverflow.com&sca_esv=ebc234f9216407d8&sxsrf=ACQVn09LQpbpbXzJRaUIXCgN-Vpa_a5zXQ:1712326020273&sa=X&ved=2ahUKEwj26bXBn6uFAxXKyDgGHY4FAwIQrQIoBHoECB4QBQ&biw=1272&bih=598&dpr=1.5)


# NumPy Joining Array
- [W3school](https://www.w3schools.com/python/numpy/numpy_array_join.asp)
- [Numpy Documentation](https://numpy.org/doc/stable/reference/generated/numpy.concatenate.html) (`np.concatenate`)

## Joining NumPy Arrays

Joining means putting contents of two or more arrays in a single array.

We pass a sequence of arrays that we want to join to the `concatenate` function, along with the axis. If the axis is not explicitly passed, it is taken as 0:

**Join two arrays**

In [22]:
arr1 = np.array([1,2,3])

arr2 = np.array([4,5,6])

arr  = np.concatenate((arr1,arr2))

print(arr)

[1 2 3 4 5 6]


**Join two 2-D arrays along rows (axis =1):**

In [23]:
arr1 = np.array([[1,2],[3,4]])
arr2 = np.array([[5,6],[7,8]])
arr  = np.concatenate((arr1,arr2),axis=1) 
print(arr)

[[1 2 5 6]
 [3 4 7 8]]


## Joining Arrays Using Stack Functions

Stacking is same as concatenation, the only difference is that stacking is done along with a new axis.

We can concatenate two 1-D arrays along the second axis which would result in putting them one over the other, i.e. stacking.

We pass a sequence of arrays that we want to join to the `stack()` method along with the axis. If axis is not explicitly passed it is taken as 0:

In [24]:
arr1 = np.array([1,2,3])

arr2 = np.array([4,5,6])

arr  = np.stack((arr1,arr2),axis=1)

print(arr)

[[1 4]
 [2 5]
 [3 6]]


**Stacking Along Rows**

NumPy provides a helper function: `hstack` to stack along rows

In [25]:
arr = np.hstack((arr1,arr2))
print(arr)

[1 2 3 4 5 6]


**Stacking Along Columns**

NumPy provides a helper function: `vstack()` to stack along columns

In [26]:
arr = np.vstack((arr1,arr2))
print(arr)

[[1 2 3]
 [4 5 6]]


**Stacking Along Height (depth)**

Numpy provides a helper function: `dstack` to stack along height which is the same as depth.

In [27]:
arr = np.dstack((arr1,arr2))
print(arr)

[[[1 4]
  [2 5]
  [3 6]]]


# Finding the last element of NumPy Array

- [Finxter blog](https://blog.finxter.com/5-best-ways-to-access-the-last-element-of-a-python-numpy-array/)

- [GiS Stack Exchange answers](https://gis.stackexchange.com/questions/102219/print-last-digit-in-numpy-array)

- [W3school1](https://www.tutorialspoint.com/how-to-select-elements-from-numpy-array-in-python)

- [W3school2](https://www.tutorialspoint.com/How-to-get-the-last-element-of-a-list-in-Python)

- [Numpy Documentation](https://numpy.org/devdocs/user/absolute_beginners.html)

## Method 1: Using Negative Indexing

Negative indexing allows us to count from the end of the array. In NumPy, `array[-1]` will return the last element of the array. 

In [28]:
# Create a NumPy array
arr = np.array([1,2,3,4,5])

# Access the last element
last_element = arr[-1]
print(last_element)
type(last_element)

5


numpy.int32

## Method 2: Using the `item` Method

The `item()` method in NumPy can be used to retrieve a specific element from an array. By passing `-1` as the argument, it retrieves the last element. This method is beneficial when you require the native Python scalar type instead of NumPy type.

In [29]:
# Access the last element as a native Python type
last_element = arr.item(-1)
print(last_element)
type(last_element)

5


int

## Method 3: Using the `take` function

The `take()` is a flexible way to access elements of a NumPy array by specifying the indices. To retrieve the last element you can pass `-1` as the index to the `take()` function.

In [30]:
last_element =  np.take(arr,-1)
print(last_element)
type(last_element)

5


numpy.int32

## Method 4: Using the `index` Function with `shape`

Another way to access the last element of a NumPy array is to use the array's shape to calculate the index of the last element. The `shape` attribute returns a tuple that represents the size of each dimension of the array. You can use this compute the index of the last element.

In [31]:
#Calculate the index of the last element
last_index = arr.shape[0]-1

#Access the last element
print(arr.shape[0])
last_element = arr[last_index]
print(last_element)
type(last_element)

5
5


numpy.int32

## Method 5: Using the `flat` Attribute (One-Liner)

The `flat` attributes provides a 1-D iterator over the array. We can combine this with the `[-1]` index to get the last element in a clean one-liner. 

In [32]:
# Access the last element using the `flat` attribute
last_element = arr.flat[-1]
print(last_element)
type(last_element)

5


numpy.int32